### PR TITLE
Update photography-guidelines.md

### PR DESCRIPTION
**Pull request by goddesswarship**
Added clarification that video files can't be used for ID even though they can be uploaded.

### CODE REVIEW

**Review by TanyaStere42 — CHANGES_REQUESTED** [review]
I'd make this addition at least an info, if not a warning. see `/security/my-account.html` for example formatting

**Review by TanyaStere42 — COMMENTED** [review]
I think the format is supposed to be like: https://github.com/WildMeOrg/wildbook-docs/blob/5ebc6af2536d0c73a0df32b6448ca74da252c32c/docs/security/my-account.md?plain=1#L27

**Comment by goddesswarship** [comment]
I followed the guidance for alerts in the Github Markdown docs: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

It looked ok in the preview. I can change it, though. I'm just confused with which markdown style I should reference for edits going forward.

**Review by TanyaStere42 — COMMENTED** [review]
AH! That's my mistake (and why I need to get the contribution guide together). We're using sphinx with a markdown extension called myst-parser (https://myst-parser.readthedocs.io/en/latest/syntax/optional.html) so the formatting for some syntax isn't traditional markdown. I should have explained that when I referenced the page with the correct formatting. Sorry about that!

**Review by TanyaStere42 — APPROVED** [review]

**Pull request merged**
